spring:
  application:
    name: clinica-med
  datasource:
    url: jdbc:postgresql://localhost:5432/clinica-medica
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc.batch_size: 50
        show_sql: true
        format_sql: true


logging:
  level:
    root: info
    org.springframework.web: debug


server:
  port: 8089
  error:
    include-stacktrace: never

application:
  security:
    jwt:
      secret-key: 4cd06563-0f1e-44db-bd4c-ea92839347f0
      expiration: 720 # minutes

